# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"  # Switched to "dark" skin for a professional look

# Site Settings
locale: "en-US"
title: "Rubab's Portfolio"
title_separator: "-"
subtitle: "Portfolio showcasing my projects, experience, and skills"
name: "Rubab Ajmal"  # Replace with your full name
description: "A portfolio highlighting my engineering experience, projects, and technical skills."
url: "https://rubab32.github.io"  # Replace with your GitHub Pages URL
baseurl: "/portfolio"  # Specify the repo name if not serving from root
repository: "https://github.com/rubab32/portfolio"  # Replace with your GitHub username/repo
teaser: "/assets/images/teaser-image.png"  # Add a teaser image in assets if desired
logo: "/assets/images/logo.png"  # Add a logo in the assets directory if available
masthead_title: "My Portfolio"
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
copyright: "Rubab Ajmal"  # Replace with your name for copyright
copyright_url: "https://rubab32.github.io"  # Replace with your website URL

# Comments settings (optional)
comments:
  provider: false

# Social Sharing
social:
  type: "Person"
  name: "Rubab Ajmal"
  links:
    - label: "GitHub"
      url: "https://github.com/rubab32"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/rubab-ajmal-150a17b8/"

# Site Author
author:
  name: "Rubab Ajmal"
  avatar: "/assets/images/avatar.jpg"  # Replace with the path to your avatar image
  bio: "I am a Robotics Engineer specializing in Manipulators and SLAM."
  location: "Rochester, New York"
  email: "rubab.ajmal@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rubab32"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rubab-ajmal-150a17b8/"

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# GitHub Pages gem for supported plugins
gem: "github-pages"
group: :jekyll_plugins
